# Generated by Django 5.2.7 on 2025-11-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_options_alter_topic_options_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_others_posts', 'Może edytować posty innych użytkowników')]},
        ),
    ]
